### PR TITLE
fix recreateViews

### PR DESCRIPTION
**Pull request by t7costa**
you can't remove views in the same loop since the positions change

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Hey there, thanks for the PR.

Do you have an example of when/where this was causing issues?

**Comment by t7costa** [comment]
Sure - if you create an adapter with 10 items, then replace it with 5 items and call notifyDataSetChanged() the resulting view would have 7 items. This is happening because the code tries to remove the child views by position 5,6,7,8,9 in that order - but once we remove child 5 the positions all shift back by one so we actually need to remove the child at position 5 each time instead (or remove it as a range like in my PR).

**Comment by Jawnnypoo** [comment]
Awesome, thanks for catching this issue!

**Comment by Jawnnypoo** [comment]
Released as 1.1.1

**Pull request merged**
